on:
  workflow_call:
    inputs:
      run-name:
        required: false
        description: 'The name shown when executed'
        type: string
      VAR1:
        required: false
        description: 'Variable 1'
        type: string
      OUTPUT1 :
        required: false
        description: 'Output 1'
        type: string
      OUTPUT2 :
        required: false
        description: 'Output 2'
        type: string
name: SAST
run-name: ${{ inputs.run-name }}
jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: jmorenocastillo/clonerepo
        
      - run: |
          echo "Scanning...${{ inputs.VAR1 }}"
          echo "Output 1: ${{ inputs.OUTPUT1 }}"
          echo "Output 2: ${{ inputs.OUTPUT2 }}"
        
      - name: Process file
        env:
          ENV_NAME: ${{ inputs.OUTPUT1 }}"  # Pasar variable al script
          VERSION: ${{ inputs.OUTPUT2 }}"
        shell: bash
        run: |
          cd prueba
          ls -la
          echo "Processing file: ${{ inputs.OUTPUT1 }}"
          echo "file processed" >> ${{ inputs.OUTPUT2 }}
          chmod +x deploy.sh
          echo "::set-output name=result::$(bash script.sh ${{ inputs.OUTPUT1 }} ${{ inputs.OUTPUT2 }})"



        