on:
  workflow_call:
    inputs:
      run-name:
        required: false
        description: 'The name shown when executed'
        default: 'Running SAST 🚀'
        type: string
      VAR1:
        required: false
        description: 'Variable 1'
        default: 'default value'
        type: string
name: SAST
run-name: ${{ inputs.run-name }}
jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Scanning..."