on:
  workflow_call:
    inputs:
      run-name:
        required: false
        description: 'The name shown when executed'
        type: string
      VAR1:
        required: false
        description: 'Variable 1'
        type: string
      OUTPUT1 :
        required: false
        description: 'Output 1'
        type: string
      OUTPUT2 :
        required: false
        description: 'Output 2'
        type: string
name: SAST
run-name: ${{ inputs.run-name }}
jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Scanning...${{ inputs.VAR1 }}"
          echo "Output 1: ${{ inputs.OUTPUT1 }}"
          echo "Output 2: ${{ inputs.OUTPUT2 }}"