name: Reusable Workflow
on:
  workflow_call:
jobs:
  reusable-job:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar artifact
        uses: actions/download-artifact@v3
        with:
          name: config-file
      - name: Leer configuraci칩n
        id: read-config
        run: |
          echo "param1=$(jq -r '.param1' config.json)" >> $GITHUB_OUTPUT
          echo "param11=$(jq -r '.param11' config.json)" >> $GITHUB_OUTPUT
      - name: Usar par치metros
        run: |
          echo "Par치metro 1: ${{ steps.read-config.outputs.param1 }}"
          echo "Par치metro 11: ${{ steps.read-config.outputs.param11 }}"